// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateMasterPassword(arg1:string,arg2:boolean):Promise<void>;

export function GenerateGiftToken(arg1:number):Promise<string>;

export function GetSettings():Promise<backend.Settings>;

export function GetVaults():Promise<Array<backend.Vault>>;

export function HasExistingData():Promise<boolean>;

export function HasMasterPassword():Promise<boolean>;

export function ImportGiftToken(arg1:string,arg2:string):Promise<void>;

export function IsConfigured():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFilesDialog():Promise<Array<string>>;

export function OpenFolderDialog():Promise<string>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartDelete(arg1:number):Promise<void>;

export function StartDownload(arg1:number):Promise<void>;

export function StartUpload(arg1:Array<string>,arg2:boolean,arg3:boolean):Promise<void>;

export function TestConnection():Promise<void>;

export function UnlockWithPassword(arg1:string):Promise<void>;
