// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['CreateMasterPassword'](arg1, arg2);
}

export function GenerateGiftToken(arg1) {
  return window['go']['main']['App']['GenerateGiftToken'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVaults() {
  return window['go']['main']['App']['GetVaults']();
}

export function HasExistingData() {
  return window['go']['main']['App']['HasExistingData']();
}

export function HasMasterPassword() {
  return window['go']['main']['App']['HasMasterPassword']();
}

export function ImportGiftToken(arg1, arg2) {
  return window['go']['main']['App']['ImportGiftToken'](arg1, arg2);
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function StartDelete(arg1) {
  return window['go']['main']['App']['StartDelete'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartUpload'](arg1, arg2, arg3);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function UnlockWithPassword(arg1) {
  return window['go']['main']['App']['UnlockWithPassword'](arg1);
}
